version: '3'

vars:
  binary: myapp

tasks:
  lint:
    desc: "Запуск golangci-lint для проверки кода"
    cmds:
      - golangci-lint run
    silent: true

  test:
    desc: "Запуск всех тестов"
    cmds:
      - go test -v ./...
    silent: true

  build:
    desc: "Сборка исполняемого файла"
    cmds:
      - go build -o {{.binary}}
    silent: true

  run:
    desc: "Запуск приложения"
    cmds:
      - go run cmd/app/main.go
    silent: true

  clean:
    desc: "Удаление скомпилированных файлов"
    cmds:
      - rm -f {{.binary}}
    silent: true

  deps-update:
    desc: "Обновление всех модулей go"
    cmds:
      - go get -u ./...
      - go mod tidy
    silent: true

  fmt:
    desc: "Форматирование исходного кода"
    cmds:
      - go fmt ./...
    silent: true

  vet:
    desc: "Запуск go vet для статического анализа"
    cmds:
      - go vet ./...
    silent: true

  coverage:
    desc: "Запуск тестов с отчетом покрытия"
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out
    silent: true
